<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Components\Layout\Shared\" />
    <Folder Include="Components\Layout\Store\" />
    <Folder Include="Components\Pages\Admin\KhoHang\" />
    <Folder Include="Components\Pages\Admin\DonHang\" />
    <Folder Include="Components\Pages\Admin\BaoCaoDoanhThu\" />
    <Folder Include="Components\Pages\Admin\BaoCaoSanPham\" />
    <Folder Include="Components\Pages\Admin\ThongTinCuaHang\" />
    <Folder Include="Components\Pages\Admin\ThanhToan\" />
    <Folder Include="Components\Pages\Admin\XuatKho\" />
    <Folder Include="Components\Pages\Admin\NhapKho\" />
    <Folder Include="Components\Pages\Admin\ThuongHieu\" />
    <Folder Include="wwwroot\assets\images\" />
    <Folder Include="wwwroot\assets\fonts\" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

</Project>
