<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application.Assets\Application.Assets.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="TextProcessing">
      <HintPath>..\..\..\..\Users\ADMIN\source\repos\CoffeeShopTest\Data\TextProcessing.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
